# .github/workflows/dependency-graph.yml
name: Update Dependency Graph
on:
  push:
    branches:
      - master # default branch of the project
jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-24.04 # noble
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: sbt/setup-sbt@3afe9cf056c5d139bfc46579af1192d77a2f0821 # v1.4.0
      - uses: scalacenter/sbt-dependency-submission@d84eef4c09e633bcf5f113bcad7fd5e9af1baee9 # v3.2.3
        env:
          JFROG_USERNAME: ${{ secrets.ARTIFACTORY_READONLY_TOKEN_USER }}
          JFROG_PASSWORD: ${{ secrets.ARTIFACTORY_READONLY_TOKEN }}
