name: Update lockfile

on:
  pull_request:
    types: [labeled,opened,reopened,synchronize]
    branches: [ master ]

jobs:
  update_lockfile:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'auto-lockfile-update')
    environment: CI

    timeout-minutes: 20

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        name: Checkout repository
        with:
          ref: ${{ github.head_ref }}

      - name: Set up JDK 17
        uses: coursier/setup-action@fd1707a76b027efdfb66ca79318b4d29b72e5a02 # v3.0.0
        with:
          jvm: temurin:17
          apps: sbt

      - name: Update lock
        run: sbt -Dsbt.log.noformat=true +dependencyLockWrite

      - name: Set dummy timestamp in lockfiles
        run: |
          for f in build.*.sbt.lock; do
            sed -i"" 's/"timestamp" : ".*"/"timestamp" : "1970-01-01T00:00:00.000000000Z"/' "$f"
          done

      - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          add: 'build.*.sbt.lock'
          message: 'Update lockfiles'
          author_name: 'github-actions'
